"""Add inventory audit models

Revision ID: 692d425f260e
Revises: 20260607_01_smartping_drips
Create Date: 2026-06-09 14:54:17.261106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '692d425f260e'
down_revision: Union[str, None] = '20260607_01_smartping_drips'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_audits',
    sa.Column('outlet_id', sa.String(), nullable=False),
    sa.Column('audit_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='auditstatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.String(), nullable=True),
    sa.Column('match_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.uid'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_inventory_audits_outlet_id'), 'inventory_audits', ['outlet_id'], unique=False)
    op.create_index(op.f('ix_inventory_audits_status'), 'inventory_audits', ['status'], unique=False)
    op.create_table('inventory_audit_items',
    sa.Column('audit_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('system_quantity', sa.Integer(), nullable=True),
    sa.Column('physical_quantity', sa.Integer(), nullable=True),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['inventory_audits.uid'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_inventory_audit_items_audit_id'), 'inventory_audit_items', ['audit_id'], unique=False)
    op.create_index(op.f('ix_inventory_audit_items_product_id'), 'inventory_audit_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_audit_items_product_id'), table_name='inventory_audit_items')
    op.drop_index(op.f('ix_inventory_audit_items_audit_id'), table_name='inventory_audit_items')
    op.drop_table('inventory_audit_items')
    op.drop_index(op.f('ix_inventory_audits_status'), table_name='inventory_audits')
    op.drop_index(op.f('ix_inventory_audits_outlet_id'), table_name='inventory_audits')
    op.drop_table('inventory_audits')
    op.execute("DROP TYPE IF EXISTS auditstatus")
    # ### end Alembic commands ###
